### ISSUE TITLE
star侧边栏无法显示

### ISSUE THREAD

**Issue by akkuman** [lvxianchao/the-fucking-github#3]
一直在转圈圈
![](https://ww1.sinaimg.cn/large/006Fzy5igy1g24cq5ycukj31hc0qe43j.jpg)

**Comment by lvxianchao** [comment]
重新开启页面也是这个样子吗？

**Comment by akkuman** [comment]
是的，从昨天到今天就一直是这个样子，浏览器电脑重启过

**Comment by lvxianchao** [comment]
有查看控制台吗？有没有看到什么报错信息？

**Comment by akkuman** [comment]
```
app.js:1 Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'TheFuckingGithub' exceeded the quota.
    at t.value (chrome-extension://agajobpbaphiohkbkjigcalebbfmofdo/js/app.js:1:670826)
    at gi.n.write (chrome-extension://agajobpbaphiohkbkjigcalebbfmofdo/js/app.js:1:669452)
    at gi.<anonymous> (chrome-extension://agajobpbaphiohkbkjigcalebbfmofdo/js/app.js:1:669346)
    at Wt (chrome-extension://agajobpbaphiohkbkjigcalebbfmofdo/js/app.js:1:117445)
    at gi.t [as write] (chrome-extension://agajobpbaphiohkbkjigcalebbfmofdo/js/app.js:1:145244)
    at chrome-extension://agajobpbaphiohkbkjigcalebbfmofdo/js/app.js:1:1266819
value @ app.js:1
n.write @ app.js:1
(anonymous) @ app.js:1
Wt @ app.js:1
t @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
(anonymous) @ app.js:1
c @ app.js:1
(anonymous) @ app.js:1
e.(anonymous function) @ app.js:1
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
Promise.then (async)
D @ app.js:1
a @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
getStarredList @ app.js:1
mounted @ app.js:1
qe @ app.js:1
tn @ app.js:1
insert @ app.js:1
E @ app.js:1
(anonymous) @ app.js:1
e._update @ app.js:1
i @ app.js:1
hn.get @ app.js:1
hn @ app.js:1
(anonymous) @ app.js:1
Cn.$mount @ app.js:1
Cn.$mount @ app.js:1
Cn._init @ app.js:1
Cn @ app.js:1
(anonymous) @ app.js:1

```

**Comment by lvxianchao** [comment]
原来是你的数据量太大，本地存储不够用了。

**Comment by akkuman** [comment]
那这个有办法解决吗

**Comment by lvxianchao** [comment]
我思考一下解决办法，但恐怕这个问题彻底解决之前，你都无法正常使用这个插件了，真的很抱歉。

**Comment by akkuman** [comment]
好哒，十分感谢

**Comment by lvxianchao** [comment]
不客气，谢谢你的支持！

**Comment by wujunchuan** [comment]
如果换成`IndexedDB API`可以存入的数据量会大一点

**Comment by lvxianchao** [comment]
@wujunchuan 是的，我正打算更换存储驱动。

**Comment by lvxianchao** [comment]
@akkuman 嗨！你愿意将你的 token 借我测试一下吗？我暂时无法模拟出你这么多的数据量。

**Comment by akkuman** [comment]
@lvxianchao email给我，我发你

**Comment by lvxianchao** [comment]
@akkuman coderlxc@gmail.com 谢谢支持！

**Comment by akkuman** [comment]
@lvxianchao 这个token好像现在无法显示了，你的程序里面哪里能看到吗

**Comment by akkuman** [comment]
@lvxianchao 没有的话我就新生成一个

**Comment by lvxianchao** [comment]
@akkuman 在 localstorage 里面可以看到。我想到一个办法模拟大量的数据，所以你的 token 不用发了，哈哈。

谢谢！

**Comment by akkuman** [comment]
@lvxianchao 好的

**Comment by lvxianchao** [comment]
@akkuman 嗨，我想我可能解决了这个问题，你可以再生成一个临时的 Token 以帮助我测试吗？一旦真的解决了这个问题我就马上通知你删除掉这个临时的 Token 。

**Comment by lvxianchao** [comment]
@akkuman 嗨，我上传了最新的版本，其版本号是：1.0.2。如果对于你的账号仍然无法使用，我们可以继续在这里讨论。

**Comment by akkuman** [comment]
ok，已经可以显示了
